export const timesheet = [{
  title: '',
  dataIndex: 'title',
  key: 'title',
  width: 100,
  className: 'timesheetTitleFeilds'
}, {
  title: 'Sun',
  dataIndex: 'sun',
  key: 'sun',
  width: 100,
  className: 'timesheetSunday'
}, {
  title: 'Mon',
  dataIndex: 'mon',
  key: 'mon',
  width: 100,
}, {
  title: 'Tue',
  dataIndex: 'tue',
  key: 'tue',
  width: 100,
}, {
  title: 'Wed',
  dataIndex: 'wed',
  key: 'wed',
  width: 100,
}, {
  title: 'Thur',
  dataIndex: 'thur',
  key: 'thur',
  width: 100,
}, {
  title: 'Fri',
  dataIndex: 'fri',
  key: 'fri',
  width: 100,
}, {
  title: 'Sat',
  dataIndex: 'sat',
  key: 'sat',
  width: 100,
  className: 'timesheetSaturday'
}];