export const SIGN_UP = '/signup/'
export const SIGN_IN = '/signin/'
export const PASSWORD_FORGET = '/pw-forget/'

export const CLIENTPORTAL = '/'
export const TIMESHEETS = '/timesheets/'
export const SITEPLANTREGISTER = '/site-plant-register/'
export const NONCONFORMANCE = '/non-conformance-register/'
export const INCIDENTREGISTER = '/incident-register/'
export const SQESTATS = '/sqe-stats/'
export const HAZARDREGISTER = '/hazard-register/'
export const PLANTVERIFICATION = '/plant-verification/'
export const JOB = '/job/'

export const PROFILE = '/profile/'
