export const timesheet = [{
  title: '',
  dataIndex: 'title',
  key: 'title',
  width: 100,
  className: 'timesheetTitleFeilds'
}, {
  title: 'Sunday',
  dataIndex: 'sun',
  key: 'sun',
  width: 100,
}, {
  title: 'Monday',
  dataIndex: 'mon',
  key: 'mon',
  width: 100,
}, {
  title: 'Tuesday',
  dataIndex: 'tue',
  key: 'tue',
  width: 100,
}, {
  title: 'Wednesday',
  dataIndex: 'wed',
  key: 'wed',
  width: 100,
}, {
  title: 'Thursday',
  dataIndex: 'thur',
  key: 'thur',
  width: 100,
}, {
  title: 'Friday',
  dataIndex: 'fri',
  key: 'fri',
  width: 100,
}, {
  title: 'Saturday',
  dataIndex: 'sat',
  key: 'sat',
  width: 100,
}];
